swagger: '2.0'
info:
  version: '1.0.0'
  title: Task-Manager
host: localhost:9010
basePath: /api
consumes: [application/json]
produces: [application/json]
paths:
  /task:
    get:
      tags: [Get]
      summary: 'Get Tasks from database'
      description: 'It returns Task objects of task that are found in the mongodb database'
      operationId: Task
      responses:
        200:
          description: 'Successfully Found Tasks in Databases'
          schema:
            type: object
            properties:
              ID:
                type: string
                example: "64fe0c46464203251e7ad828"
              Description:
                type: string
                example: "Book a massage for Tuesday"
              DueDate:
                type: string
                example: "By Monday"
            required:
              - Description
              - DueDate
        400:
          description: Bad Request
        404:
          description: Task Not Found
        500:
          schema:
            type: string
          description: Server Error
  /task/{taskId}:
    get:
      tags: [Get]
      summary: "Returns a Task by ID."
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: string
            minimum: 1
      responses:
        200:
          schema:
            type: object
            properties:
              ID:
                type: string
                example: 64fe0c46464203251e7ad828
              Description:
                type: string
                example: "Book flights for tuesday"
              DueDate:
                type: string
                example: "By Monday"
            required:
              - Description
              - DueDate
          description: Successfully found Task with id {taskId} in Database
        400:
          description: Bad request
        404:
          description: Task Not Found
        500:
          schema:
            type: string
          description: Server Error
    post:
      tags: [ Create ]
      summary: Create a new task
      description: Create a new task with the provided data
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              Description:
                type: string
              DueDate:
                type: string
              Completed:
                type: boolean
            required:
              - Description
              - DueDate
      responses:
        '201':
          description: Task created successfully
        '400':
          description: Bad request - Invalid input
        '500':
          description: Internal server error
    put:
      tags: [Edit]
      summary: 'Edit Task'
      description: 'edit any task by using task id'
      operationId: Task
      responses:
        200:
          description: 'Successfully edited Task'
          schema:
            type: object
            properties:
              ID:
                type: string
                example: "64fe0c46464203251e7ad828"
              Description:
                type: string
                example: 'Book a message for tuesday'
              DueDate:
                  type: string
                  example: "By sunday"
              Completed:
                type: boolean
                example: false
            required:
              - Description
              - DueDate
              - Completed
        400:
          description: Bad Request
        404:
          description: Task Not Found
    delete:
      tags: [Delete]
      summary: 'Delete Task'
      description: 'Delete any task by using task id'
      operationId: Task
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: string
            minimum: 1
      responses:
        200:
          description: 'Succesfully deleted Task {taskId}'
          schema:
            type: object
            properties:
              ID:
                type: string
                example: "64fe0c46464203251e7ad828"
              Description:
                type: string
                example: 'Book a message for tuesday'
              DueDate:
                type: string
                example: "By sunday"
              Completed:
                  type: boolean
                  example: false
            required:
              - Description
              - DueDate
              - Completed
        400:
          description: Bad Request
        404:
          description: Task Not Found
